# This is a basic workflow to help you get started with Actions
##github actions has its own language like name, run

name: Deploy Website ##CI, any name 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: ##event, on which events occurence you want to execute jobs:commands in reaction 
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: ##which commands to execute in reaction to on:events, assumption:github actions trigger small VM or some docker application on github server to execute commands in ubuntu
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2 ##as this machine donot have our code, so this command clones our github repository
    # Runs a single command using the runners shell
    
    ##C1
    - name: Install NodeJS ##from now onwards we will be using our commands as this is an isolated machine and needed the softwares to be installed
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    ##C2
    - name: Install Surge
      run: npm install -g surge
    
    ##C3
    - name: Run Surge
      run: surge ./ anasbaigmughal-bootcamp2020.surge.sh --token ${{secrets.SURGE_TOKEN}} ##current folder, path where code exists which you wanna deploy and the address of surge where you want to  deploy and the token to be found from local machine as 'surge token' command and then add it in bootcamp settings secret and then add it here as the same name
##ERRORS Mean
##every step must define a `uses` or `run` key
## dash '-' is with name only, if you want to add dash with each command like name, run etc then you have to again add 'uses' section with that command
